import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({subsets: ['latin']})
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";


export const metadata: Metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main className="container">{children}</main>
        <Footer/>
        </body>
    </html>
  );
}
